### ISSUE TITLE
Help I got an error 

### ISSUE THREAD

**Issue by Naiml007** [akashyap2013/Supabase_UserManagement_React#1]
Error: Warning: Invalid DOM property &#x60;class&#x60;. Did you mean &#x60;className&#x60;?
    at input
    at form
    at div
    at div
    at Auth (https://f6190af1-734f-415b-bb99-19c667a06e08.id.repl.co/static/js/bundle.js:372:80)
    at div
    at App (https://f6190af1-734f-415b-bb99-19c667a06e08.id.repl.co/static/js/bundle.js:38:80)https://f6190af1-734f-415b-bb99-19c667a06e08.id.repl.co/static/js/bundle.js:372

**Comment by Naiml007** [comment]
But Auth working
